### ISSUE TITLE
Chunk Size is not correct

### ISSUE THREAD

**Issue by JasjeH** [caliskanmurat/qgis_raster_divider_plugin#2]
I have problem with the size of the chunks. I've set it to 1000x1000 px, however the output rasters have different size (1162x811 px). 
What is happening? Is the output size somehow related to the size of the input raster?

Thanks in advance

**Comment by caliskanmurat** [comment]
Hello,
Can you send me the raster file if it is not large and not confidential?
Let me check. I haven't encounter such an error so far.

Sincerely.
Murat Caliskan


24 Kas 2022 Per 18:05 tarihinde JasjeH ***@***.***> şunu
yazdı:

**Comment by caliskanmurat** [comment]
The bug was fixed and plugin was uploaded the repo.
